export const TOGGLE_RECORDING = "TOGGLE_RECORDING";
export const SELECT_METRIC_SET = "SELECT_METRIC_SET";
export const ZOOM_METRIC = "ZOOM_METRIC";
export const UPDATE_CHART = "UPDATE_CHART";
export const UPDATE_PERIOD_TYPE = "UPDATE_PERIOD_TYPE";
export const UPDATE_INTERVAL_FOR_RUNNING_RECORDING = "UPDATE_INTERVAL_FOR_RUNNING_RECORDING";
